### ISSUE TITLE
can't build on windows with dmd 2.086.0

### ISSUE THREAD

**Issue by John-Colvin** [MartinNowak/io#20]
```
dub build --arch=x86_64
Performing "debug" build using C:\D\dmd2\windows\bin\dmd.exe for x86_64.
io 0.2.2: building configuration "library"...
src\std\io\file.d(357,20): Error: std.io.file.File.__ctor called with argument types (void*) matches both:
src\std\io\file.d(169,9):     std.io.file.File.this(void* handle)
and:
src\std\io\file.d(365,5):     std.io.file.File.this(return scope void* f)
C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
```

**Comment by damianday** [comment]
Can't build with 2.088.1 either.

**Comment by schveiguy** [comment]
I'll get this working.
