### PR TITLE
Fix #20 disambiguate windows handles from std.io FILE

### LINKED ISSUE #20: can't build on windows with dmd 2.086.0
```
dub build --arch=x86_64
Performing "debug" build using C:\D\dmd2\windows\bin\dmd.exe for x86_64.
io 0.2.2: building configuration "library"...
src\std\io\file.d(357,20): Error: std.io.file.File.__ctor called with argument types (void*) matches both:
src\std\io\file.d(169,9):     std.io.file.File.this(void* handle)
and:
src\std\io\file.d(365,5):     std.io.file.File.this(return scope void* f)
C:\D\dmd2\windows\bin\dmd.exe failed with exit code 1.
```

### PR DESCRIPTION
**Pull request by John-Colvin**

### CODE REVIEW

**Comment by schveiguy** [comment]
I'm not understanding what this is accomplishing. You have an example of why this is necessary?

**Comment by schveiguy** [comment]
Ah, ok I now read the bug report. I think this is a backwards approach, `std.io.FILE` is an internal thing, we should change that and not wrap what people have normally.

Though I'm not sure it should be a typedef. Maybe something like an opaque struct:

```D
struct FILE
{
   void *_handle;
}
```

And deal with the nitty gritty inside wherever it's used.

**Comment by schveiguy** [comment]
And, we should have unittests for this. I'm surprised it builds, but maybe because these constructors aren't being used.

**Comment by schveiguy** [comment]
I fixed this in #23
